# Book settings
title: Games on graphs
author: "a set of authors coordinated by Nathana&euml;l Fijalkow"
copyright: "2021"
logo: 'cover.jpg'

bibtex_bibfiles:
   - 1_bib.bib
   - 2_bib.bib
   - 3_bib.bib
   - 4_bib.bib
   - 5_bib.bib

only_build_toc_files: true

sphinx:
  extra_extensions:
    - sphinx_proof
  config:
    html_theme_options:
      use_download_button: False
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
