# Book settings
title: Games on graphs
author: a set of authors coordinated by Nathana&euml;l Fijalkow
logo: 'cover.jpg'

bibtex_bibfiles:
   - bib.bib

latex:
  latex_documents:
    targetname: book.tex

# def setup(app):
#     app.add_stylesheet('custom.css')

sphinx:
  extra_extensions:
    - sphinx_proof

sphinx:
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

sphinx:
  config:
    mathjax_config:
      TeX:
        Macros:
          "set"    : ["\\left\\{ #1 \\right\\}", 1]
          "N"      : "\\mathbb{N}"
          "Z"      : "\\mathbb{Z}"
          "Q"      : "\\mathbb{Q}"
          "Qinfty" : "\\Q \\cup \\set{\\infty}"
          "R"      : "\\mathbb{R}"
          "Rinfty" : "\\R \\cup \\set{\\infty}"

          "ing"    :  "\\text{In}"
          "Ing"    :  "\\ing"
          "out"    :  "\\text{Out}"
          "Out"    :  "\\out"
          "first"  :  "\\text{first}"
          "last"   :  "\\text{last}"
          "Paths"  :  "\\text{Paths}"
          "play"   :  "\\pi"

          "arena"  :  "\\mathcal{A}"
          "Arena"  :  "\\arena"
          "col"    :  "\\textsf{col}"
          "Col"    :  "\\col"
          "game"   :  "\\mathcal{G}"
          "Game"   :  "\\game"

          "Eve"    :  "\\mathrm{Eve}"
          "Adam"   :  "\\mathrm{Adam}"
          "VE"     :  "V_\\Eve"
          "VA"     :  "V_\\Adam"
          "VR"     :  "V_\\mathrm{Random}"
          "WE"     :  "W_\\Eve"
          "WA"     :  "W_\\Adam"
          "Value"  :  "val"
          "val"    :  "\\Value"
          "ValueE" :  "\\Value_\\Eve"
          "ValueA" :  "\\Value_\\Adam"

          "Win"    :  "\\text{Win}"
          "Lose"   :  "\\text{Lose}"

          "Safe"             :  "\\mathtt{Safe}"
          "Reach"            :  "\\mathtt{Reach}"
          "Buchi"            :  "\\mathtt{Buchi}"
          "CoBuchi"          :  "\\mathtt{CoBuchi}"
          "Parity"           :  "\\mathtt{Parity}"
          "MeanPayoff"       :  "\\mathtt{MeanPayoff}"
          "DiscountedPayoff" :  "\\mathtt{DiscountedPayoff}"

          "Automaton"        :  "\\mathbf{A}"

          "half"             :  "\\frac{1}{2}"
