# Book settings
title: Games on graphs
author: "a set of authors coordinated by Nathana&euml;l Fijalkow"
copyright: "2021"
logo: 'Illustrations/cover.jpg'

bibtex_bibfiles:
   - Bib/1_bib.bib
   - Bib/2_bib.bib
   - Bib/3_bib.bib
   - Bib/4_bib.bib
   - Bib/5_bib.bib
   - Bib/6_bib.bib
   # - Bib/7_bib.bib
   - Bib/8_bib.bib
   - Bib/9_bib.bib
   - Bib/10_bib.bib
   - Bib/11_bib.bib
   - Bib/12_bib.bib
   - Bib/13_bib.bib

only_build_toc_files: true

sphinx:
  extra_extensions:
    - sphinx_proof
  config:
    html_theme_options:
      use_download_button: False
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
